# Generated by Django 5.2 on 2025-05-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_storeowner_redeemedreward_store_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemedreward',
            name='store_owner',
        ),
        migrations.RemoveField(
            model_name='redeemedreward',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='redeemedreward',
            name='qr_image',
        ),
        migrations.RemoveField(
            model_name='redeemedreward',
            name='status',
        ),
        migrations.AddField(
            model_name='submitproof',
            name='coins_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitproof',
            name='earned_coins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitproof',
            name='image_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submitproof',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submitproof',
            name='proof_image',
            field=models.FileField(upload_to='proofs/'),
        ),
        migrations.DeleteModel(
            name='StoreOwner',
        ),
    ]
