# Generated by Django 5.2.3 on 2025-06-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_redeemedreward_store_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitproof',
            name='plant_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submitproof',
            name='activity_type',
            field=models.CharField(choices=[('Tree Plantation', 'Tree Plantation'), ('Solar Panel Installation', 'Solar Panel Installation'), ('Public Transport Usage', 'Public Transport Usage'), ('Use of Electric Vehicle', 'Use of Electric Vehicle')], max_length=100),
        ),
    ]
