# Generated by Django 5.2.3 on 2025-07-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_submitproof_plant_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitproof',
            name='image_action',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/tree_stages/'),
        ),
        migrations.AddField(
            model_name='submitproof',
            name='image_after_planting',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/tree_stages/'),
        ),
        migrations.AddField(
            model_name='submitproof',
            name='image_empty_spot',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/tree_stages/'),
        ),
        migrations.AlterField(
            model_name='submitproof',
            name='proof_image',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
