# Generated by Django 5.2.3 on 2025-07-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_submitproof_image_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitproof',
            name='image_empty_spot',
        ),
    ]
